server {
    listen 80;
    server_name identity-hub;

    location / {
        proxy_pass http://identityhub:8084;
        proxy_set_header Host identity-hub;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
