#!/usr/bin/env python3
"""Store pre-signed JWT credentials in Identity Hub.

Reads a JSON file of credentials (generated by create-credentials.py) and
stores each one in the Identity Hub via the Identity API.

Prerequisites:
    - Identity Hub deployed and accessible (port 29082 exposed by default)
    - API key: docker exec identityhub-vault vault kv get -field=content secret/super-user-apikey

Usage:
    python3 scripts/store-credentials.py [credentials.json] [--url URL] [--api-key KEY]

    Defaults:
        credentials.json: ./credentials.json
        URL: http://localhost:8082
        API key: reads from IH_API_KEY env var
"""

import json
import os
import sys
import urllib.request
import urllib.error


def store_credentials(credentials_file, ih_url, api_key):
    with open(credentials_file) as f:
        credentials = json.load(f)

    success = 0
    failed = 0

    for cred in credentials:
        bpn = cred["bpn"]
        cred_type = cred["type"]
        jwt_token = cred["jwt"]
        vc = cred["vc"]

        body = {
            "participantContextId": bpn,
            "verifiableCredentialContainer": {
                "rawVc": jwt_token,
                "format": "VC1_0_JWT",
                "credential": vc
            }
        }

        url = f"{ih_url}/api/identity/v1alpha/participants/{bpn}/credentials"
        data = json.dumps(body).encode()
        req = urllib.request.Request(url, data=data, method="POST")
        req.add_header("Content-Type", "application/json")
        req.add_header("x-api-key", api_key)

        try:
            resp = urllib.request.urlopen(req)
            print(f"  {bpn} / {cred_type}: OK (HTTP {resp.status})")
            success += 1
        except urllib.error.HTTPError as e:
            error_body = e.read().decode()
            print(f"  {bpn} / {cred_type}: FAIL (HTTP {e.code}) - {error_body}")
            failed += 1
        except Exception as e:
            print(f"  {bpn} / {cred_type}: ERROR - {e}")
            failed += 1

    print(f"\n  Results: {success} stored, {failed} failed")
    return failed == 0


def main():
    credentials_file = sys.argv[1] if len(sys.argv) > 1 else "credentials.json"
    ih_url = os.environ.get("IH_URL", "http://localhost:8082")
    api_key = os.environ.get("IH_API_KEY", "")

    # Parse --url and --api-key flags
    args = sys.argv[1:]
    for i, arg in enumerate(args):
        if arg == "--url" and i + 1 < len(args):
            ih_url = args[i + 1]
        elif arg == "--api-key" and i + 1 < len(args):
            api_key = args[i + 1]

    if not api_key:
        print("ERROR: API key required. Set IH_API_KEY env var or use --api-key flag.")
        print("  Get it from: docker exec identityhub-vault vault kv get -field=content secret/super-user-apikey")
        sys.exit(1)

    if not os.path.exists(credentials_file):
        print(f"ERROR: Credentials file not found: {credentials_file}")
        print("  Generate it first: python3 scripts/create-credentials.py > credentials.json")
        sys.exit(1)

    print(f"  IH URL: {ih_url}")
    print(f"  Credentials: {credentials_file}")
    print()

    ok = store_credentials(credentials_file, ih_url, api_key)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
